USE 中文北風
GO

SELECT 員工編號,姓名,稱呼,雇用日期,薪資
FROM 員工
--WHERE 薪資>=60000;
--WHERE 薪資>=50000 AND 薪資<=60000;
--WHERE 薪資<40000 OR 薪資>70000;
--WHERE 雇用日期'2002.1.1 00:00:00';可用/ .,沒打時間會自動補上
WHERE 雇用日期 BETWEEN '2002.1.1' AND '2002.12.31 23:59:59';

/*盡可能不要在Where部分使用函數
1. 搜尋時間變慢
2. 導致索引無法二分搜尋法→索引掃描
*/

--YEAR、MONTH、DAY
--DATEPART(單位,日期時間)
SELECT DATEPART(YEAR,GETDATE())
SELECT DATEPART(DAYOFYEAR,GETDATE()) --一年中的第幾天
SELECT DATEPART(QUARTER,GETDATE()) --第幾季
SELECT DATEPART(WEEKDAY,GETDATE()) --第幾週
SELECT DATEPART(MILLISECOND,GETDATE()) --毫秒
SELECT SYSDATETIME(); --DATETIME2


--DATEADD(單位,數量,日期時間)
SELECT DATEADD (DAY,3,SYSDATETIME())  --+3 day
SELECT DATEADD (WEEK,3,SYSDATETIME())  --+3週
SELECT DATEADD (HOUR,300,SYSDATETIME()) --+300 hoyr
SELECT DATEADD (DAY,-20,SYSDATETIME())  ---20天

--DATED(單位,較早時間,較晚時間)
SELECT DATEDIFF(DAY,GETDATE(),'2022-9-10') --相差天數
SELECT DATEDIFF(HOUR,GETDATE(),'2022-9-10')/24

--計算function
SELECT ABS(-5);
SELECT ROUND(56.789,2);
SELECT ROUND(56.789,-1);
SELECT CEILING(7.3) --得到>=這數值最接近的整數
SELECT FLOOR(7.3)  --得到<=這數值最接近的整數
SELECT POWER(3,4);  --次方
SELECT SQRT(81) --開根號
SELECT RAND(52) --0<= ~ <1



SELECT 員工編號,姓名,稱呼,職稱,出生日期,薪資
FROM 員工
WHERE YEAR(GETDATE())-YEAR(出生日期) <= 40 OR YEAR(GETDATE())-YEAR(出生日期)>=65;
--WHERE 出生日期>DATTEADD(YEAR,-40,GETDATE)
--WHERE 出生日期>DATTEADD(YEAR,-65,GETDATE)

--不在Where中使用函數
DECLARE @detel DATE=DATEADD(YEAR,-65,GETDATE());
SELECT 員工編號,姓名,稱呼,職稱,出生日期,薪資
FROM 員工
WHERE 出生日期<@detel;


/* CAST / CONVERT 格式轉換
CAST(值 AS 目標型別)
CONVERT(目標型別,值[,格式參數])
*/
SELECT '巨匠'+CAST(100 AS NVARCHAR)
SELECT '巨匠'+CONVERT(NVARCHAR,100)

--建構日期
SELECT DATEFROMPARTS(2010,10,10)
SELECT DATETIMEFROMPARTS(2010,10,10,10,20,30,123)
SELECT DATETIME2FROMPARTS(2010,10,10,10,20,30,123,5)

--EOMONTH 得到該月的最後一天
SELECT EOMONTH(GETDATE())
SELECT EOMONTH('2022-05-05')

SELECT DATEADD(DAY,1,EOMONTH(DATEADD(MONTH,-2,GETDATE())))
SELECT EOMONTH(DATEADD(MONTH,-1,GETDATE()))


DECLARE @date1 DATE=DATEADD(DAY,1,EOMONTH(DATEADD(MONTH,-2,GETDATE())));
DECLARE @date2 DATE=EOMONTH(DATEADD(MONTH,-1,GETDATE()));
SELECT 員工編號,姓名,稱呼,職稱,雇用日期,薪資
FROM 員工
WHERE 雇用日期>=@date1 AND 雇用日期<@date2;


SELECT DATEADD(MONTH,-6,GETDATE())
SELECT DATEADD(DAY,1,EOMONTH(DATEADD(MONTH,-7,GETDATE())))
